<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="Categories.aspx.cs" Inherits="CeeLearnAndDo.Admin.Categories" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title><%=pageTitle%></title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="page_header_title" runat="server">
    <%=contentTitle%>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="page_header_breamcrumb" runat="server">
    <%=breadCrumb%>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="content" runat="server">
    <section class="overview-header">
        <asp:Button ID="btnNewCat" CssClass="btn btn-default" runat="server" Text="New Category" OnClick="btnNewCat_Click" />
    </section>
    <section class="overview">
        <asp:GridView ID="GridView1" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" runat="server" GridLines="None" CssClass="table table-striped" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="CatName" HeaderText="Category" SortExpression="CatName" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT * FROM [Categories]"></asp:SqlDataSource>
        <asp:Panel ID="Panel1" runat="server">
            <div class="add">
                <hr style="border-color: #CCC;" />
                <h2>Add a new Category</h2>
                <asp:TextBox ID="txtCatTitle" CssClass="form-control" placeholder="Enter category title.." runat="server"></asp:TextBox>
                <br /><asp:Button ID="btnAddCat" CssClass="btn btn-primary" runat="server" Text="Add Category" OnClick="btnAddCat_Click" />
            </div>
        </asp:Panel>
    </section>
</asp:Content>
