<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="References.aspx.cs" Inherits="CeeLearnAndDo.Admin.References" ValidateRequest="false" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title><%=pageTitle%></title>
    <script>
        function jsToAsp() {
            var input = $('#summernote').code();
            document.getElementById("HiddenField1").value = input;
        }

        function jsToAspEdit() {
            var input = $('#summernote').code();
            document.getElementById("HiddenField2").value = input;
        }
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="page_header_title" runat="server">
    <%=contentTitle%>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="page_header_breamcrumb" runat="server">
    <%=breadCrumb%>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="content" runat="server">
    <%
        if (Request.QueryString["action"] == "overview")
        {
    %>

    <section class="overview-header">
        <a class="btn btn-default" href="References.aspx?action=new" role="button">New Reference</a>
    </section>
    <section class="overview">        
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" GridLines="None" CssClass="table table-striped" AutoGenerateColumns="False" DataSourceID="SqlDataSource">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:HyperLinkField DataTextField="Title" DataNavigateUrlFields="Id" DataNavigateUrlFormatString="~/Admin/References.aspx?action=edit&Id={0}" HeaderText="Title" />
                <asp:BoundField DataField="DateAdded" HeaderText="DateAdded" SortExpression="DateAdded" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT * FROM [Reference]"></asp:SqlDataSource>
        
    </section>
    <%
        }
        else if (Request.QueryString["action"] == "new")
        {
    %>
    <div class="add">
        <div class="row">
            <div class="col-md-9">
                <asp:TextBox ID="txtTitle" CssClass="form-control" placeholder="Enter your title here.." autofocus="autofocus" runat="server"></asp:TextBox>
                <div class="input">
                    <div id="summernote"></div>
                    <asp:HiddenField ClientIDMode="Static" ID="HiddenField1" runat="server" />
                </div>
            </div>
            <div class="col-md-3">
                <div class="postbox">
                    <h3>Publish your post</h3>
                    <div class="inside">
                        <div class="actions">
                            <a href="#">Nevermind</a><asp:Button ID="butPublish" OnClientClick="jsToAsp()" CssClass="btn btn-primary mtopbut" runat="server" Text="Publish" OnClick="butPublish_Click" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%
        }
        else if (Request.QueryString["action"] == "edit")
        {
    %>
    <div class="add">
        <div class="row">
            <div class="col-md-9">
                <asp:TextBox ID="EditTitle" CssClass="form-control" placeholder="Enter your title here.." autofocus="autofocus" runat="server"></asp:TextBox>
                <div class="input">
                    <div id="summernote"><%= editContent %></div>
                    <asp:HiddenField ClientIDMode="Static" ID="HiddenField2" runat="server" />
                </div>
            </div>
            <div class="col-md-3">
                <div class="postbox">
                    <h3>Publish your post</h3>
                    <div class="inside">
                        <div class="actions">
                            <a href="~/Admin/References.aspx?action=overview">Nevermind</a><asp:Button ID="btnEdit" OnClientClick="jsToAspEdit()" CssClass="btn btn-primary mtopbut" runat="server" Text="Publish" OnClick="btnEdit_Click" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%
        }
        else
        {
    %>
    <span style="color: red; font-size: 36pt;">404 ERROR</span>
    <%
        }
    %>
</asp:Content>
